/**
 * IDE Component (Client-side)
 
 * Each challenge's pseudocode is written and tested using this IDE.
 
 * Instructions: Provides a description of the task, hint, and example-solution.
 * Code Editor: Allows users to write and modify pseudocode. Once run, it is processed with a backend API for Test Results.
 * Test Results: Displays the raw-output and outcome of each test case. This includes a pass/fail based on actual/expected output and any runtime errors.
 
 * The containers for instructions, code editor, and results can be maximized/minimized to enhance user-control.
*/

import React, { useState, useEffect, useRef } from "react";
import Navbar from "../../../components/nav_bar";
import Instructions from "./ide_components/instructions/instructions";
import Editor from "./ide_components/editor/editor";
import Results from "./ide_components/results/results";

import "./ide_styles.css";
// pages/code-editor.tsx

// Define the type for the test result object
export type TestResultType = {
  status:
    | "Pass"
    | "Fail"
    | "Pending"
    | "Syntax Error"
    | "Runtime Error"
    | "Fail (Multiple Outputs)"
    | "Special Error";
  actual: string[]; // Array of actual outputs generated by the backend
  expected: any; // Expected output (depends on your test case structure)
  input: any[]; // Input for the test case
};

// Define the props for the IDE component, which includes challenge data, test cases, and metadata
interface IDEProps {
  id: number;
  title: string;
  description: string;
  hint: string;
  tags: string[];
  difficulty: string;
  testCases: { inputs: string[]; output: string }[]; // Test case structure
  exampleCode: string;
  outputType: any;
  testInputsTypes: {
    name: string;
    type: string;
  }[];
}

const IDE: React.FC<IDEProps> = ({
  id,
  title,
  description,
  hint,
  tags,
  difficulty,
  testCases,
  exampleCode,
  outputType,
  testInputsTypes,
}) => {
  // State variables for handling the code, test results, and UI components
  const [completeStatus, setCompleteStatus] = useState<boolean | undefined>();
  const [code, setCode] = useState<string>(""); // Stores the pseudocode written by the user
  const [output, setOutput] = useState<string[]>([]); // Stores the output from the backend
  const [isComplete, setIsComplete] = useState<boolean>(false); // Indicates whether all test cases have been processed

  const [expandInstructions, setExpandInstructions] = useState<boolean>(false); // Toggles instruction panel visibility
  const [expandEditor, setExpandEditor] = useState<boolean>(false); // Toggles editor panel visibility
  const [expandResults, setExpandResults] = useState<boolean>(false); // Toggles results panel visibility

  const [instructionState, setInstructionState] = useState<"task" | "solution">("task"); // Tracks whether the instructions show task or solution

  const testIndexRef = useRef<number>(0); // Tracks the index of the current test case being processed

  // State for managing the test results, initialized to 'Pending'
  const [testResults, setTestResults] = useState<TestResultType[]>(
    testCases.map((testCase) => ({
      status: "Pending", // Initial status of each test case
      actual: [],
      expected: testCase.output,
      input: testCase.inputs,
    }))
  );

  // Toggle between task and solution view for instructions
  const toggleInstructionState = () => {
    setInstructionState((prevState) =>
      prevState === "task" ? "solution" : "task"
    );
  };

  // State to toggle between outcome and raw output for results
  const [resultState, setResultState] = useState<"outcome" | "output">("outcome");

  const toggleResultsState = () => {
    setResultState((prevState) =>
      prevState === "outcome" ? "output" : "outcome"
    );
  };

  // Effect to check if test cases are available
  useEffect(() => {
    if (!testCases) {
      testIndexRef.current = -1; // -1 means playground mode, no test cases
    }
  }, [testCases]);

  // Effect to manage panel visibility (only one panel should be visible at a time)
  useEffect(() => {
    if (expandInstructions) {
      setExpandEditor(false);
      setExpandResults(false);
    }
  }, [expandInstructions]);

  useEffect(() => {
    if (expandEditor) {
      setExpandInstructions(false);
      setExpandResults(false);
    }
  }, [expandEditor]);

  useEffect(() => {
    if (expandResults) {
      setExpandInstructions(false);
      setExpandEditor(false);
    }
  }, [expandResults]);

  // Function to send API request to the backend to run the pseudocode for a specific test case
  const fetchFromBackend = async (
    isLast: boolean,
    test_case_index: number
  ) => {
    if (code.trim()) {
      try {
        // Send API request with pseudocode and test case data
        const response = await fetch("/api/index/run_code", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            pseudocode: code, // Your pseudocode
            test_case_input_name: testInputsTypes, // Input name
            test_case_input_value: testCases[test_case_index]?.inputs, // Input value
            test_case_index: test_case_index, // Test case index
          }),
        });

        // Parse the JSON response
        type ApiResponse =
          | { error: string }
          | { result: string; status: string };

        const result: ApiResponse = await response.json();

        // Handle response based on status
        if ("error" in result) {
          console.log("Handled Error:", result.error);
          handleBackendResponse(result.error, isLast, true);
        } else if ("result" in result && result.status === "success") {
          console.log("Success:", result.result);
          handleBackendResponse(result.result, isLast, false);
        } else {
          console.error("Unexpected response:", result);
          alert("An unexpected error occurred.");
        }
      } catch (error) {
        console.error("Unexpected response:", error);
        alert("An unexpected error occurred. Please try again later.");
      }
    }
  };

  // Update the code in the editor as the user types
  const handleEditorChange = (value: string | undefined) => {
    setCode(value || "");
  };

  // Trigger the backend request for each test case when the "Run Code" button is clicked
  const handleRunCode = async () => {
    setOutput([]); // Clear previous output
    setIsComplete(false); // Reset completion state
    testIndexRef.current = 0; // Start from the first test case
    setTestResults(
      testCases.map((testCase) => ({
        status: "Pending", // Reset test case status
        actual: [],
        expected: testCase.output,
        input: testCase.inputs,
      }))
    ); // Reset test results to their initial state

    processNextTestCase(); // Start processing test cases
  };

  // Process the backend response for a test case (check for errors, success, or failure)
  const handleBackendResponse = (
    data: any,
    isLast: boolean,
    isError: boolean
  ) => {
    const currentIndex = testIndexRef.current;

    if (!testCases[currentIndex]) {
      console.error("No test case found at index:", currentIndex);
      return;
    }

    const uuid = "49e7d449-5214-4b8f-8743-888c6009c227"; 
    // This UUID is an output-marker used in the API-compiler to indicate an expression is intended to be outputted.

    if (!isError && isLast) {
      setOutput((prev) => [
        ...prev,
        "=".repeat(3) + " Output Hidden " + "=".repeat(3)
      ]);
    } else {
      setOutput((prev) => [
        ...prev,
        data.replace(new RegExp(uuid + " ", "g"), "") + "\n",
      ]); // Append new output of the current test case to that of prior cases.
    }

    const currentTest = testCases[currentIndex];

    // Extract valid outputs using regex
    const outputRegex = new RegExp(`${uuid}\\s(.*?)(?:\\n|$)`, "g");
    const validOutputs: any = [];
    let match;

    while ((match = outputRegex.exec(data)) !== null) {
      validOutputs.push(match[1]);
    }

    // Determine the test case status
    let status: TestResultType["status"] = "Pending";

    if (data.includes("Syntax Error")) {
      status = "Syntax Error";
    } else if (data.includes("Runtime Error")) {
      status = "Runtime Error";
    } else if (validOutputs.length > 1) {
      status = "Fail (Multiple Outputs)";
    } else if (
      data.includes("Error: Pseudocode argument missing") ||
      data.includes("Error: Failed to convert pseudocode to Python") ||
      data.includes("Error during conversion")
    ) {
      status = "Special Error";
    } else if (validOutputs[0] === currentTest.output) {
      status = "Pass";
    } else {
      status = "Fail";
    }

    // Update the test results for the current test case
    setTestResults((prevResults) => {
      const updatedResults = [...prevResults];
      updatedResults[currentIndex] = {
        ...updatedResults[currentIndex],
        status,
        actual: validOutputs.length > 1 ? validOutputs[0] : validOutputs,
      };
      return updatedResults;
    });

    // Move to the next test case
    testIndexRef.current += 1;
    processNextTestCase();
  };

  // Process the next test case, or mark the process as complete
  const processNextTestCase = async () => {
    let isLast = false;
    if (testIndexRef.current >= testCases.length) {
      console.log("All test cases processed");
      setIsComplete(true); // All test cases have processed by the API.
      return;
    } else if (testIndexRef.current === testCases.length - 1) {
      isLast = true;
    }

    setIsComplete(false);

    setOutput((prev) => [
      ...prev,
      "=".repeat(3) + ` Running Test Case ${testIndexRef.current + 1} ` + "=".repeat(3),
    ]);

    await fetchFromBackend(isLast, testIndexRef.current);
  };

  // Pass necessary props for the subcomponents (Instructions, Editor, Results)
  const instructionArgs = {
    id: id,
    title: title,
    description: description,
    hint: hint,
    tags: tags,
    difficulty: difficulty,
    testCases: testCases,
    expandInstructions: expandInstructions,
    setExpandInstructions: setExpandInstructions,
    instructionState: instructionState,
    toggleInstructionState: toggleInstructionState,
    outputType: outputType,
    inputName: testInputsTypes,
    exampleSolution: exampleCode,
    completeStatus: completeStatus,
    testInputsTypes: testInputsTypes,
  };

  const editorArgs = {
    id: id,
    code: code,
    onCodeChange: setCode,
    onRun: handleRunCode,
    expandEditor: expandEditor,
    setExpandEditor: setExpandEditor,
  };

  const resultsArgs = {
    id: id,
    output: output,
    isComplete: isComplete,
    onClearOutput: () => setOutput([]),
    expandResults: expandResults,
    setExpandResults: setExpandResults,
    resultState: resultState,
    toggleResultsState: toggleResultsState,
    testResults: testResults,
    setCompleteStatus: setCompleteStatus,
    testInputsTypes: testInputsTypes,
  };

  return (
    <div id="IDE" className="flex flex-col h-screen bg-zinc-950">
      <Navbar />
      <div id="IDE_Panel" className="flex flex-row flex-grow overflow-hidden">
        {expandInstructions && (
          <Instructions width={"w-[100%] m-5"} {...instructionArgs} />
        )}

        {expandEditor && <Editor width={"w-[100%] m-5"} {...editorArgs} />}

        {expandResults && <Results width={"w-[100%] m-5"} {...resultsArgs} />}

        {!expandInstructions && !expandEditor && !expandResults && (
          <>
            <Instructions width={"w-[35%]"} {...instructionArgs} />

            <div className="divider flex flex-col flex-grow justify-between gap-6 w-[65%]">
              <div className="h-[49%]">
                <Editor width={"flex-grow"} {...editorArgs} />
              </div>
              <div className="h-[49%] flex-grow">
                <Results width={"flex-grow"} {...resultsArgs} />
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default IDE;
